# dicord-pr-notification.yml
name: Notify Discord on PR Creation

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  notify-discord:
    uses: byui-formula-hybrid/Core/.github/workflows/discord-pr-notify.yml@main
