# dicord-pr-notification.yml
name: Notify Discord on PR Creation

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  notify-discord:
    uses: byui-formula-hybrid/.github/.github/workflows/discord-pr-notification.yml@main
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      DISCORD_ROLE_ID: ${{ secrets.DISCORD_ROLE_ID }}